wificountry=
wifissid=
wifipassword=
gituser=cms66
gitrepo=rpi-homehq
defsysdir=/usr/local
defdatadir=/data/current
gitlocaldir=/data/current/src/git
cams=("imx708" "imx219" "ov5647")
subnet=192.168.0.0/24
